device: cpu
root_dir: _models_trained/causal_nf/
seed: 1000
dataset:
  root: Data/
  name: treatment_hmdaNY
  sem_name: dummy
  splits: [ 0.8,0.1,0.1 ]
  k_fold: 1
  shuffle_train: True
  loss: default
  scale: default
  add_noise: True
  num_sensitive: 2
  num_covariate: 12
  num_treatment: 2
  categorical_dims: [0, 1, 2, 3, 4, 5, 9, 15, 16]
model:
  name: causal_nf
  layer_name: nsf
  dim_inner: [ 32, 32 ]
  num_layers: 1
  init: None
  act: elu
  adjacency: True
  base_to_data: False
  plot: False
train:
  max_epochs: 1000
  regularize: False
  kl: forward
  batch_size: 512
  num_workers: 0
  limit_train_batches: None
  limit_val_batches: None
  max_time: 00:05:00:00
  inference_mode: False
optim:
  optimizer: adam
  base_lr: 0.01
  beta_1: 0.9
  beta_2: 0.999
  momentum: 0.0
  weight_decay: 0.0
  scheduler: plateau
  gamma: 0.99
  step_size: 100
  mode: min
  factor: 0.9
  patience: 60
  cooldown: 0