device: cpu
root_dir: _models_trained/causal_nf/
seed: 1000
dataset:
  root: Data/
  name: treatment_synthetic
  sem_name: dummy
  splits: [ 0.8,0.1,0.1 ]
  k_fold: 1 # Not sure if this should be increased.
  shuffle_train: True
  loss: default
  scale: default
  add_noise: True
  num_sensitive: 2 # Give correct
  num_covariate: 3 # Give correct
  num_treatment: 2 # Give correct
  categorical_dims: [0,7]
model:
  name: causal_nf
  layer_name: nsf  # used in paper for German
  dim_inner: [16,16,16,16]  # used in paper for German
  num_layers: 1
  init: None
  act: elu
  adjacency: True
  base_to_data: False
  plot: False
train:
  max_epochs: 1000
  regularize: False
  kl: forward  # backward
  batch_size: 128
  num_workers: 0
  limit_train_batches: None
  limit_val_batches: None
  max_time: 00:05:00:00
  inference_mode: False
optim:
  optimizer: adam
  base_lr: 0.001 #0.001 # Paper mentions 0.01 for German.
  beta_1: 0.9
  beta_2: 0.999
  momentum: 0.0
  weight_decay: 0.0
  scheduler: plateau
  gamma: 0.99
  step_size: 100
  mode: min
  factor: 0.9
  patience: 60
  cooldown: 0


