seed: [ 1000 ]
device: [ cpu ]
root_dir: [ hparam_grid_causal_mods/comparison_causal_nf ]
dataset:
  name: 'TODO'
  sem_name: 'TODO'
  root: [ Data/]
  splits: [ [ 0.8, 0.1, 0.1 ] ]
  k_fold: [ 1 ]
  shuffle_train: [ True ]
  loss: [ default ]
  scale: [ default ]
  add_noise: [ True ]
  num_sensitive: 'TODO'
  num_covariate: 'TODO'
  num_treatment: 'TODO'
  categorical_dims: 'TODO'
model:
  name: [ causal_nf ]
  layer_name: [ nsf ]
  dim_inner: [ [ 16, 16, 16 , 16 ],  [ 32, 32, 32 ],  [ 16, 16, 16 ],   [ 32, 32 ],  [ 32 ] , [ 64 ] ]
  num_layers: [ 1 ]
  init: [ None ]
  act: [ elu ]
  adjacency: [ True ]
  base_to_data: [ False ]
  plot: [ False ]
train:
  max_epochs: [ 1000 ]
  regularize: [ False ]
  batch_size: [ 256 ]
  inference_mode: [ False ]
  max_time: [ 00:10:00:00 ]
  enable_progress_bar: [ False ]
optim:
  optimizer: [ adam ]
  base_lr: [1e-2, 1e-3]
  beta_1: [ 0.9 ]
  beta_2: [ 0.999 ]
  momentum: [ 0.0 ]
  weight_decay: [ 0.0 ]
  scheduler: [ plateau ]
  mode: [ min ]
  factor: [ 0.9 ]
  patience: [ 60 ]
  cooldown: [ 0 ]
